default: &default 
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: phn001
  password: phn001

development: &development
  <<: *default
  database: ancar_development

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: *development

test:
  <<: *default
  database: ancar_test
