default: &default
  adapter: sqlserver
  mode: dblib
  host: localhost
  port: 1433

development: &development
  <<: *default
  database: GPWRPT
  username: GPNUSUU
  password: GPNUSUU

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
production:
  adapter: sqlserver
  mode: dblib
  timeout: 5000
  reconnect: false
  database: GPWRPT
#  encoding: unicode
  host: sql05vs05\sql05vs05.munimadrid.es
  port: 1433
  pool: 5
  username: GPNUSUU
  password: GPNUSUU

