development:
  adapter: sqlserver
  mode: dblib
  host: 10.90.51.153
  port: 2685
  mode: dblib
  database: GPWRPT
  username: GPNUSUU
  password: jg17PR9x

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
production:
  adapter: sqlserver
  host: 10.90.51.153
  port: 2685
  mode: dblib
  timeout: 5000
  reconnect: false
  database: GPWRPT
  pool: 5
  username: GPNUSUU
  password: jg17PR9x
